apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: default  # Or the appropriate namespace where Jenkins is running

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-cluster-admin
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: default  # Or the appropriate namespace
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Secret
metadata:
  name: jenkins-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: jenkins
type: kubernetes.io/service-account-token