apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-audio-storage
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  local:
    # path: /home/kt/Sem_6/RecSys/Project/darbar_audio
    path: /app/audio_files
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
