apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2  # Number of backend replicas
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ketakitam/backend-image:latest  # Replace with your backend image
        ports:
        - containerPort: 8000
        volumeMounts:
            - name: audio-storage
              mountPath: /app/audio_files # Path in the container where audio files will be accessible
      volumes:
        - name: audio-storage
          persistentVolumeClaim:
            claimName: audio-files-pvc # PVC that this Pod will use
        # env:
        # - name: STORJ_API_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: vault-secret
        #       key: STORJ_API_KEY
        # - name: STORJ_BUCKET_NAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: vault-secret
        #       key: STORJ_BUCKET_NAME

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 32001
  type: NodePort  # Internal service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2  # Number of frontend replicas
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ketakitam/frontend:latest  # Replace with your frontend image
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 4000       # External port exposed by the service
      targetPort: 3000  # Internal port that React app listens on
      nodePort: 32000   # Choose a port number between 30000-32767
  type: NodePort   # Change from LoadBalancer to NodePort
